# Generated by Django 3.1.1 on 2020-09-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('app', models.CharField(max_length=30)),
                ('apm', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descrpcion', models.TextField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('identifcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.user')),
            ],
        ),
    ]
