# Generated by Django 3.1.2 on 2020-10-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20200925_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='check.user'),
        ),
    ]
