# Generated by Django 3.1.2 on 2020-10-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_auto_20201015_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='clasificacion',
            field=models.CharField(choices=[('ORGANIZACION', 'ORGANIZACION'), ('TAREA', 'TAREA'), ('RECORDATORIO', 'RECORDATORIO'), ('IMPORTANTE', 'IMPORTANTE'), ('URGENTE', 'URGENTE')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='notas',
            name='tipo',
        ),
        migrations.AddField(
            model_name='notas',
            name='tipo',
            field=models.ManyToManyField(to='check.Categoria'),
        ),
    ]
