# Generated by Django 3.1.2 on 2020-10-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_auto_20201021_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='clasificacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CategoriaNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.categoria')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.notas')),
            ],
        ),
        migrations.RemoveField(
            model_name='notas',
            name='tipo',
        ),
        migrations.AddField(
            model_name='notas',
            name='tipo',
            field=models.ManyToManyField(through='check.CategoriaNota', to='check.Categoria'),
        ),
    ]
