# Generated by Django 3.1.2 on 2020-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20201023_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorianota',
            name='opciones',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ORGANIZACION'), (2, 'TAREA'), (3, 'RECORDATORIO'), (4, 'IMPORTANTE'), (5, 'URGENTE')], null=True),
        ),
    ]
